spring:
  datasource:
    username: root
    password: 123456
   #使用 MySQL连接驱动是8.0以上，需要在Url后面加上时区, GMT%2B8代表中国时区，不然报时区错误
    url: jdbc:mysql://127.0.0.1:3306/jpa?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver


  #jpa的配置
  jpa:
    # 控制台打印sql
    show-sql: true
    hibernate:
      # 会根据就映射实体类自动创建或更新数据表
      ddl-auto: update
    # 默认创建表类型是MyISAM，是非事务安全的，所以无法实现事物回滚
    # 指定如下方言: 创建的表类型是Innodb，才可以进行对事物的回滚。
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
